plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Pragnyan\\dev\\getmymarket\\frontend\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "pnpm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]